## Introduction to Numpy

If not installed in requirements.txt we can try-

<span style="color:orange">!pip install numpy</span>

In [ ]:
# Create a 1D array - no rows & columns
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(len(arr)) # returns element in an array
print(arr.shape) 
'''arr.shape provides the dimensions of the array (like rows and columns). 
Only available in NumPy'''

[1 2 3 4 5]
<class 'numpy.ndarray'>
5
(5,)


In [9]:
# Create 2D array
import numpy as np
arr1 = [1,2,3,4,5]
arr2 = [5,6,7,8,9]
new_arr = np.array([arr1 , arr2])
# new_arr = np.array(arr1+arr2) # concatenate, not 2D
print(new_arr)
print(new_arr.shape)

[[1 2 3 4 5]
 [5 6 7 8 9]]
(2, 5)


In [ ]:
# np.arange(start,end,steps) 
'''it's arange not arrange'''
import numpy as np
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [18]:
# np.reshape(rows,columns)
arr = np.arange(5,15,2)
arr.reshape(5,1)

array([[ 5],
       [ 7],
       [ 9],
       [11],
       [13]])

In [ ]:
# np.ones(rows,columns) - all elements will be 1
'''if 
np.ones() - single bracket..
NumPy expects the shape of the array to be a single tuple
not multiple separate arguments.'''
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
# Identity matrix
np.eye(3) # N×N square matrix
np.eye(2,3) # NxM
np.eye(4,3,1) # NxMxK; k = # Shift diagonal k step to the right col

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# Slicing & Indexing(row x col)
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr,'\n')
# print(arr.shape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 



In [57]:
print(arr[0][3],end=' ')
print(arr[1][2],end=' ')
print(arr[2][1],end=' ')
print(arr[0][0],end=' ')
print('\n')
print(arr[1:,2:])
print('\n')
print(arr[1:,2:])
print('\n')
print(arr[0:2,2:])
print('\n')
print(arr[1:3,1:]) # arr[1:,1:]
print('\n')
print(arr[1:3,1:3])


4 7 10 1 

[[ 7  8]
 [11 12]]


[[ 7  8]
 [11 12]]


[[3 4]
 [7 8]]


[[ 6  7  8]
 [10 11 12]]


[[ 6  7]
 [10 11]]
