## Introduction to Numpy

If not installed in requirements.txt we can try-

<span style="color:orange">!pip install numpy</span>

In [ ]:
# Create a 1D array - no rows & columns
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(len(arr)) # returns element in an array
print(arr.shape) 
'''arr.shape provides the dimensions of the array (like rows and columns). 
Only available in NumPy'''

[1 2 3 4 5]
<class 'numpy.ndarray'>
5
(5,)


In [9]:
# Create 2D array
import numpy as np
arr1 = [1,2,3,4,5]
arr2 = [5,6,7,8,9]
new_arr = np.array([arr1 , arr2])
# new_arr = np.array(arr1+arr2) # concatenate, not 2D
print(new_arr)
print(new_arr.shape)

[[1 2 3 4 5]
 [5 6 7 8 9]]
(2, 5)


In [ ]:
# np.arange(start,end,steps) 
'''it's arange not arrange'''
import numpy as np
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [18]:
# np.reshape(rows,columns)
arr = np.arange(5,15,2)
arr.reshape(5,1)

array([[ 5],
       [ 7],
       [ 9],
       [11],
       [13]])

In [ ]:
# np.ones(rows,columns) - all elements will be 1
'''if 
np.ones() - single bracket..
NumPy expects the shape of the array to be a single tuple
not multiple separate arguments.'''
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
# Identity matrix
np.eye(3) # N×N square matrix
np.eye(2,3) # NxM
np.eye(4,3,1) # NxMxK; k = # Shift diagonal k step to the right col

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# Slicing & Indexing(row x col)
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr,'\n')
# print(arr.shape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 



In [57]:
print(arr[0][3],end=' ')
print(arr[1][2],end=' ')
print(arr[2][1],end=' ')
print(arr[0][0],end=' ')
print('\n')
print(arr[1:,2:])
print('\n')
print(arr[1:,2:])
print('\n')
print(arr[0:2,2:])
print('\n')
print(arr[1:3,1:]) # arr[1:,1:]
print('\n')
print(arr[1:3,1:3])


4 7 10 1 

[[ 7  8]
 [11 12]]


[[ 7  8]
 [11 12]]


[[3 4]
 [7 8]]


[[ 6  7  8]
 [10 11 12]]


[[ 6  7]
 [10 11]]


In [66]:
# Modification of elements
arr1 = np.array([[21,22,23],[34,35,36],[57,58,59]])
print(arr1)
print('\n')
arr1[1][2] = 55
print(arr1) 
print('\n')
arr1 [2:] = 89
print(arr1)

[[21 22 23]
 [34 35 36]
 [57 58 59]]


[[21 22 23]
 [34 35 55]
 [57 58 59]]


[[21 22 23]
 [34 35 55]
 [89 89 89]]


In [70]:
### Statistical Concepts - Normalization
## Normalization = to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# Calculate mean and standard deviation
mean_of_data = np.mean(data)
std_of_data = np.std(data)

# print(mean_of_data)
# print(std_of_data)

# Normalize the data
normalized_data = (data - mean_of_data) / std_of_data
print('Normalized Data: \n',normalized_data)


Normalized Data: 
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [75]:
### Mean Median Std Variance
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean 
mean_of_data = np.mean(data)
print('Mean: ',mean_of_data)

# Median
median_of_data = np.median(data)
print('Median: ',median_of_data)

# Standard Deviation
std_of_data = np.std(data)
print('Std: ',std_of_data)

# Variance
variance_of_data = np.var(data)
print('Variance: ',variance_of_data)

Mean:  5.5
Median:  5.5
Std:  2.8722813232690143
Variance:  8.25


In [ ]:
# logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

# data > 5        # Output: array([False, False, False, False, False,  True,  True,  True,  True, True])
data[data > 5]      # Output:  array([ 6,  7,  8,  9, 10])
data[(data>=5) & (data <=8)]

array([5, 6, 7, 8])